### ISSUE TITLE
"JSON Parse Failed"

### ISSUE THREAD

**Issue by nunnoXYZ** [Harish120896/oxford-dictionary-api#2]
Hey on my testing I get "status_code":500,"status_text":"JSON Parse Failed"

what could it be ?

thanks

**Comment by Harish120896** [comment]
what was the input that you gave?
probably the mistake must be with your input or your credentials.
try correcting them if not . show me a snapshot of that particular piece of code i will try my best to correct it.

**Comment by nunnoXYZ** [comment]
Thank you for your reply indeed it was the credentials !
good work, keep rocking ;)

**Comment by lendkhoa** [comment]
I have the same issue. Double check the app_id and key but it still reports status_code":500,"status_text":"JSON Parse Failed. (The stat page reports hit) Can you please look into it? thanks
